"""empty message

Revision ID: a5cebb8e1f3a
Revises: f47cc603091a
Create Date: 2022-09-01 15:15:23.568712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5cebb8e1f3a'
down_revision = 'f47cc603091a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('complete', sa.Boolean(), nullable=False))
    op.alter_column('projects', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('projects', 'complete')
    op.drop_column('projects', 'active')
    # ### end Alembic commands ###
