"""empty message

Revision ID: f44449e030e8
Revises: 4885ba7407c0
Create Date: 2022-09-09 14:16:14.230516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44449e030e8'
down_revision = '4885ba7407c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'direct_messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'direct_messages', type_='foreignkey')
    op.drop_column('direct_messages', 'user_id')
    # ### end Alembic commands ###
